name: E-Commerce Order Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'order-service/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Make gradlew executable
        run: chmod +x ./order-service/gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          build-root-directory: order-service
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order_service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker Pull & Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST2 }}
          username: ${{ secrets.AWS_EC2_USER2 }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY2 }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/order_service:latest
            docker stop order_service
            docker rm order_service
            docker run -d --name order_service --env SPRING.DATASOURCE.URL=jdbc:mysql://${{ secrets.MYSQL_HOST }}:${{ secrets.MYSQL_PORT }}/orders --env SPRING.DATASOURCE.USERNAME=${{ secrets.MYSQL_USER }} --env SPRING.DATASOURCE.PASSWORD=${{ secrets.MYSQL_PASSWORD }} --env SPRING.JPA.HIBERNATE.DDL-AUTO=update --env SPRING.DATASOURCE.DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver --env SPRING.JWT.TOKEN=${{ secrets.JWT_TOKEN }} --env SERVICE.IP=${{ secrets.SERVICE_IP }} --env SERVICE.PRODUCT.HOST=${{ secrets.PRODUCT_SERVICE_HOST }} --env SERVICE.USER.HOST=${{ secrets.USER_SERVICE_HOST }} --env XENDIT.APIKEY=${{ secrets.XENDIT_APIKEY }} --env SPRING.KAFKA.BOOTSTRAP-SERVERS=${{ secrets.KAFKA_SERVER }} -p 8082:8080 --restart unless-stopped ${{ secrets.DOCKERHUB_USERNAME }}/order_service:latest